redshift: 0.0
# filter_type: 'CAP' # Options: 'CAP', 'cumulative', 'DSigma
filter_type: 'cumulative' # Options: 'CAP', 'cumulative', 'DSigma
load_field: true
save_field: true
rad_distance: 1000 # in kpc/h
npixels: 2000

fig_path: '../figures/2025-08/'
fig_name: 'gas_fraction_z00_field'
fig_type: 'png'
plot_error_bars: false

simulations:
  - sim_type: 'SIMBA'
    sims:
      - name: 'm50n512'
        snapshot: 151
        feedback: 's50'
      - name: 'm50n512'
        snapshot: 151
        feedback: 's50noagn'
      - name: 'm50n512'
        snapshot: 151
        feedback: 's50nox'
      - name: 'm50n512'
        snapshot: 151
        feedback: 's50nojet'
      - name: 'm50n512'
        snapshot: 151
        feedback: 's50nofb'
  - sim_type: 'IllustrisTNG'
    sims:
      - name: 'TNG100-1'
        snapshot: 99
      - name: 'TNG300-2'
        snapshot: 99
      - name: 'Illustris-1'
        snapshot: 135