redshift: 0.5
filter_type: 'DSigma' # Options: 'CAP', 'cumulative', 'DSigma
# filter_type: 'cumulative' # Options: 'CAP', 'cumulative', 'DSigma
load_field: true
save_field: true
rad_distance: 1.0 # in arcmin

plot_data: false
data_path: '../data/Fig1_Fig8_dr10_allfoot_perbin_dr6_pzbin1.npz'
data_label: 'Hadzhiyska 2024 pz1'

fig_path: '../figures/2025-09/testSZ/'
fig_name: 'DSigma_3_profiles_yz'
fig_type: 'png'
plot_error_bars: true

# fraction_type: 'baryon' # gas or baryon
# particle_types: 
#   - 'tau'
  # - 'kSZ'
  # - 'tSZ'
particle_type: 'tau'
projection: 'yz' # 'xy', 'xz', 'yz'


simulations:
  - sim_type: 'SIMBA'
    sims:
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50noagn'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nox'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nojet'
      - name: 'm50n512'
        snapshot: 125
        feedback: 's50nofb'
      - name: 'm100n1024'
        snapshot: 125
        feedback: 's50'
  - sim_type: 'IllustrisTNG'
    sims:
      - name: 'TNG100-1'
        snapshot: 67
      - name: 'TNG300-2'
        snapshot: 67
      - name: 'Illustris-2'
        snapshot: 103